- .github/PULL_REQUEST_TEMPLATE.md
-   merge 템플릿을 수정했습니다.
Close #3
> docs: merge 템플릿에 불필요한 부분 삭제

- frontend/src/App.tsx
- frontend/src/pages/LoginPage/LoginPage.tsx
> [FE] feat/init project

- backend/Dockerfile
- frontend/Dockerfile
-   java11 자동 빌드를 위한 도커파일을 추가했습니다.
-   node 16 react 자동 빌드를 위한 도커파일을 추가했습니다.
Close #14
> feat: Dockerfile 추가 (#14)

- backend/Dockerfile
> feat: Dockerfile 수정 (#16)

- frontend/src/App.tsx
- frontend/src/components/ChildDiary/DiaryCalendar.tsx
- frontend/src/components/ChildDiary/DiaryContent.tsx
- frontend/src/components/ChildDiary/DiaryContentStyles.tsx
- frontend/src/components/ChildMisson/ChildInfo.tsx
- frontend/src/components/ChildMisson/ChildInfoStyles.tsx
- frontend/src/components/ChildMisson/MissionList.tsx
- frontend/src/components/ChildMisson/MissionListItem.tsx
- frontend/src/components/ChildMisson/MissionListStyles.tsx
- frontend/src/pages/ChildPage/ChildDiaryPage/ChildDiaryPage.tsx
- frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPage.tsx
- frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionPage.tsx
- frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionPageStyles.tsx
-   아이페이지 기능 지난일기 미션 내용 틀 구현
Close #12
> Fe feat/child dairy

- frontend/src/components/ParentMain/GiveMissionButton.tsx
- frontend/src/components/ParentMain/GiveMissionButtonStyles.tsx
- frontend/src/components/ParentMain/GiveMoneyButton.tsx
- frontend/src/components/ParentMain/GiveMoneyButtonStyles.tsx
- frontend/src/components/ParentMain/MissionButton.tsx
- frontend/src/components/ParentMain/MissionButtonStyles.tsx
- frontend/src/components/ParentMain/ParentInfo.tsx
- frontend/src/components/ParentMain/ParentInfoStyles.tsx
- frontend/src/components/ParentMain/PatternButton.tsx
- frontend/src/components/ParentMain/PatternButtonStyles.tsx
- frontend/src/components/ParentMain/TradeListButton.tsx
- frontend/src/components/ParentMain/TradeListButtonStyles.tsx
- frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
-   부모 메인페이지 페이지별 이동
Close #32
> feat: 부모메인페이지 (#32)

- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Comment.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryImage.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryShare.java
- backend/src/main/resources/application.yml
-   일기장의 JPA를 구현했습니다.
OPEN #31
> feat: diary JPA 작성(#31)

- frontend/src/components/Login/Login.tsx
- frontend/src/components/SignUp.tsx/ChildSignUp.tsx
- frontend/src/components/SignUp.tsx/ParentSignUp.tsx
- frontend/src/pages/LoginPage/LoginPage.tsx
- frontend/src/pages/LoginPage/SignUpPage.tsx
-   로그인 페이지 뼈대 구현
-  회원가입 페이지 뼈대 구현
> Fe feat/common page

- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/ProfileImage.java
-   member 도메인 연관관계 맵핑 추가
Close #44
> feat: add member domain relationship mapping (#44)

- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/CommentRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryImageRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryShareRepository.java
> feat: diary JPA 중복 삭제(#31)

- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/JwtTokenProvider.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
- backend/src/main/resources/application-jwt.yml
-   secret key change and key mapping
Close #69
> feat:secret key change and key mapping (#69)

- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/ChildWrite/BottomButton.tsx
- frontend/src/components/ChildWrite/UploadPicture.tsx
- frontend/src/components/Login/Login.tsx
- frontend/src/pages/CommonPage/MenuPage.tsx
- frontend/src/store/DiaryStore.tsx
-   아이페이지를 상세 구현하는데 필요한 전반적인 틀을 구현했습니다.
> feat: 아이페이지 전반적인 틀 구현하기(#76)

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankBalanceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankDepositRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransactionRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransferRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryCreateRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAccountResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankBalanceResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankDepositResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransactionResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransferResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Transaction.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/TransactionCategory.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionCategoryRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
> fix : 다이어리 녹음, 이미지 수정

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankBalanceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankDepositRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransactionRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransferRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryCreateRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAccountResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankBalanceResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankDepositResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransactionResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransferResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Transaction.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/TransactionCategory.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionCategoryRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
> Be feat/diary api

- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryShare.java
> feat: mapping entity

- backend/build.gradle
> fix : 자바 버전 변경

- backend/Dockerfile
> fix : 도커 파일 빌드파일이름 변경

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAccountResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransactionResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializer.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Transaction.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/TransactionCategory.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
-   계좌 거래내역 조회 구현
- 계좌 잔액 조회 구현
> feat: Bank 거래내역조회, 잔액조회 구현

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankTransferRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransferResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializer.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
- 계좌 이체 API를 구현했습니다
- 자세한 형식은 포스트맨 참조해주세요
> feat: 계좌이체 API 구현 (#90)

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
> feat: 계좌이체 잔액 초과 예외 처리 (#90)

- frontend/src/components/ChildDiary/DiaryCalendar.module.css
- frontend/src/components/ChildDiary/DiaryCalendar.tsx
- frontend/src/components/ChildDiary/DiaryContent.tsx
- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/ChildWrite/BottomButton.tsx
- frontend/src/components/ChildWrite/MoodWeather.tsx
- frontend/src/components/ChildWrite/UploadPicture.tsx
- frontend/src/components/ChildWrite/VoiceRecord.tsx
- frontend/src/pages/ChildPage/ChildTradePage/ChildTradePage.tsx
- frontend/src/store/DiaryStore.tsx
-   아이페이지 중 일기쓰기 기능 서버와 통신 확인
- 아이페이지 중 일기 읽기 기능 구현
- 아이 페이지 중 거래내역 조회 기능 구현
> Fe feat/auth page

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankAnalyzeRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAnalyzeListResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAnalyzeResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankDepositResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializer.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
- 카테고리 분석 데이터 API 구현
Close #90
> feat: 카테고리 분석 데이터 API (#90)

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
- 사진 표시를 위한 API 추가를 진행했습니다.
-   기타 추가할 내용이 있다면 추가합니다.
-   없는 경우 삭제
Close #이슈번호
> feat: 사진 표시 API 추가

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAnalyzeListResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
> feat: 카테고리 분석 결과 수정

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankAuthRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- 1원 인증 요청
- 1원 인증 확인
Close #90
> feat: 1원 인증 구현

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberCreateRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberCreateServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberProfileResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/CorsConfig.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/FileExtensionFilter.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/JwtAuthenticationFilter.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializerUtil.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/FileUtil.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/RedisUtil.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
> fix: security jwt filter error

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/AlarmController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/dto/request/AlarmConfirmRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankOneDayTransactionRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/dto/request/AlarmNotifyRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/dto/response/AlarmInfoResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializerUtil.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/NotificationType.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/AlarmQueryRepository.java
> feat: 알람서비스 구현

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
- backend/src/main/resources/application-server.yml
> fix: resolve cors error

- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/ChildWrite/DiaryCalender.tsx
- frontend/src/components/ChildWrite/TradeList.tsx
- frontend/src/store/UserStore.tsx
-   아이 거래내역 조회
- 일기쓰기에서 거래내역 조회 (map함수로 틀만 다져놨음)
> feat:아이 거래내역 조회, 일기쓰기에서 거래내역 조회(#111)

- frontend/src/components/ChildDiary/DiaryCalendar.tsx
- frontend/src/components/ChildDiary/DiaryContent.tsx
- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/ChildWrite/BottomButton.tsx
- frontend/src/components/Common/AccountRegsiter.tsx
- frontend/src/components/Common/BottomNav.tsx
- frontend/src/components/ParentRegister/ParentRegister.tsx
- frontend/src/components/ParentRegister/ParentRegisterStyles.tsx
- frontend/src/pages/CommonPage/AlarmPage.tsx
- frontend/src/pages/CommonPage/MyPage.tsx
-   일기 조회 기능 구현
-   일기에서 날짜 눌러야 다른 컴포넌트 나오는 기능 구현
-  전체적으로 아이콘 적용, 글씨체 적용
> feat: 전체적인 글씨체 변경, 아이콘 추가, 마이페이지에서 프로필 사진 변경 기능 추가

- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/RedisConfig.java
-   fix: fix redis connection error
> fix: fix redis connection error

- frontend/package.json
- frontend/src/components/ChildDiary/DiaryCalendar.tsx
-   용돈 일기 작성한 날에만 달력 선택할 수 있는 기능 구현
> feat: 용돈 일기 작성한 날에만 달력 선택할 수 있는 기능 구현

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/EmailController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/EmailCheckRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberCreateRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberLoginRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/EmailCheckServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberCreateServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberLoginServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MemberQueryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/CorsConfig.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
> fix: email send error

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/EmailController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/FamilyController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberRegistFamilyRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/FamilyService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberRegistFamilyServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/FamilyQueryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MissionQueryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
- backend/src/main/resources/application-server.yml
> feat: regist child

- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/Accomplishment.java
> refactor: 미션 상태 한글수정

- backend/.gitignore
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MissionListRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MissionListServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MissionListResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MissionSummaryResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MissionQueryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MissionQueryRepository.java
> feat: 미션 리스트 기능 추가

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MissionCreateRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MissionCreateServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/AccountResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberParentHomeResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/ProfileImageResponse.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/NotificationType.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MissionQueryRepository.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-server.yml
> fix: search member error

- backend/.gitignore
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
> feat: create mission

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankAuthRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/EmitterRepository.java
> feat: 유저의 계좌 등록 로직 수정

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/AlarmController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
> feat: SSE 알림 구현

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MissionCheckRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MissionCheckServiceRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/Accomplishment.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MissionQueryRepository.java
> Be feat/member

- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/Common/AccountRegsiter.tsx
- frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
- frontend/src/components/ParentRegister/ParentRegister.tsx
- frontend/src/components/ParentTrade/ParentTradeList.tsx
- frontend/src/pages/CommonPage/AlarmPage.tsx
- frontend/src/pages/LoginPage/SignUpPage.tsx
> feat: 회원가입 예외처리

- frontend/src/components/Common/BottomNav.tsx
- frontend/src/store/UserStore.tsx
> feat: SSE 알람 기능 구현

- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
-   구현한 기능을 적습니다.
-   논의할 내용을 적습니다.
-   학습한 내용, 공유할 내용 등을 적습니다.
-   위키에 작성했다면 링크 첨부, 없는 경우 삭제
-   기타 추가할 내용이 있다면 추가합니다.
-   없는 경우 삭제
Close #이슈번호
> fix: email

- backend/build.gradle
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/EmailConfig.java
- backend/src/main/resources/application-server.yml
-   구현한 기능을 적습니다.
-   논의할 내용을 적습니다.
-   학습한 내용, 공유할 내용 등을 적습니다.
-   위키에 작성했다면 링크 첨부, 없는 경우 삭제
-   기타 추가할 내용이 있다면 추가합니다.
-   없는 경우 삭제
Close #이슈번호
> fix :email send error

- frontend/src/components/ChildMisson/MissionListItem.tsx
- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/Common/AccountRegsiter.tsx
- frontend/src/components/ParentRegister/ParentRegisterStyles.tsx
- frontend/src/components/ParentTrade/ParentTradeList.tsx
- frontend/src/pages/CommonPage/MyPage.tsx
> Fe feat/parent main page

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
> fix: 이체가 안되는 문제 수정

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
> fix: transactional error

- frontend/src/components/ParentMission/MissionRequestMission.tsx
- frontend/src/pages/CommonPage/AlarmPage.tsx
- frontend/src/pages/LoginPage/SignUpPage.tsx
- frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
> refactor : 불필요한 주석제거

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
> fix: email send error fix

- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/Common/BottomNav.tsx
- frontend/src/components/ParentTrade/ParentTradeList.tsx
- frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
- frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
-   거래내역 카테고리에 따른 아이콘 다르게 띄우는 기능구현
> feat: 거래내역 카테고리에 따른 아이콘 다르게 띄우는 기능구현

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
> fix : 서버의 시간이 안맞는 문제 디버깅

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/JwtAuthenticationFilter.java
> feat : restart jwt token filter

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
> add: alarm ignore

- frontend/src/components/ChildTrade/ChildTradeList.tsx
- frontend/src/components/ChildWrite/BottomButton.tsx
- frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPage.tsx
- frontend/src/pages/CommonPage/MyPage.tsx
- frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPage.tsx
-   헤더에 accessToken담기 (JWT 기능 구현)
>  feat: 헤더에 accessToken담기 (JWT 기능 구현)

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/AlarmController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/SSEService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
- 이미지 업로드 수정, 알림 읽음 처리 안되는 문제 수정
> feat : 이미지 업로드 수정, 알림 읽음 처리 안되는 문제 수정

- frontend/src/components/ChildMisson/MissionList.tsx
- frontend/src/components/ChildMisson/MissionListItem.tsx
- frontend/src/components/Common/BottomNav.tsx
- frontend/src/components/Login/Login.tsx
> refactor: 기능 재점검

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/DiaryRepository.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/query/DiaryQueryRepository.java
> fix: 한 날짜에 여러 일기를 쓸 수 없게 수정

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
> fix: 사진 필터 해제, 기본 프로필 설정

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MemberQueryService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/JwtAuthenticationFilter.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/RedisUtil.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MemberQueryRepository.java
> feat: add logout

- frontend/src/components/ChildRegister/ChildRegister.tsx
- frontend/src/components/ChildWrite/DiaryCalender.tsx
- frontend/src/components/Common/BottomNav.tsx
- frontend/src/components/ParentTrade/ParentTradeList.tsx
- frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPageStyles.tsx
- frontend/src/pages/LoginPage/EmailAuthPage.tsx
- frontend/src/pages/LoginPage/SignUpPage.tsx
- frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPage.tsx
- frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPageStyles.tsx
-   SSE 알림 기능 구현, Axios 통신 과정 중 발생한 에러 해결
> feat: SSE 알림 기능 구현, Axios 통신 과정 중 발생한 에러 해결

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
> fix: SSE 테스트 빌드

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/dto/request/AlarmNotifyRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/InvalidTokenEntryPoint.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
> feat: mission sse send

- backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
-   fix: accesstoken expire time
> fix: accesstoken expire time

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/TestController.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/EmailController.java
> fix: test token

- frontend/src/App.tsx
- frontend/src/components/Common/BottomNav.tsx
- frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
- frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
- frontend/src/pages/CommonPage/AccountRegisterPage.tsx
- frontend/src/pages/CommonPage/AlarmPage.tsx
- frontend/src/pages/CommonPage/MenuPage.tsx
- frontend/src/pages/CommonPage/MyPage.tsx
- frontend/src/pages/CommonPage/ShareDiaryPage.tsx
- frontend/src/pages/LoginPage/EmailAuthPage.tsx
- frontend/src/pages/LoginPage/SignUpPage.tsx
- frontend/src/pages/ParentPage/ParentGiveMoneyPage/ParentGiveMoneyPage.tsx
- frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
> refactor: 페이지 예외처리 및 리펙토링

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/dto/request/AlarmNotifyRequest.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/NotificationType.java
> feat: mission request alarm

- backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
> fix : 등록된 계좌인지 확인하는 부분 문제

- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
- backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
-   [구현한 기능을 적습니다.
-   논의할 내용을 적습니다.
-   학습한 내용, 공유할 내용 등을 적습니다.
-   위키에 작성했다면 링크 첨부, 없는 경우 삭제
-   기타 추가할 내용이 있다면 추가합니다.
-   없는 경우 삭제
Close #이슈번호](fix: mission send error)
> fix: mission send error
